# Generated by Django 5.2.3 on 2025-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sentence', models.TextField()),
                ('words', models.JSONField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
