# Generated by Django 5.2.3 on 2025-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelevel',
            options={'verbose_name': 'O‘yin bosqichi', 'verbose_name_plural': 'O‘yin bosqichlari'},
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Urinishlar soni'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Tugallanganmi'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', 'O‘rtacha'), ('hard', 'Qiyin')], max_length=20, verbose_name='Qiyinchilik darajasi'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bosqich nomi'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='sentence',
            field=models.TextField(verbose_name='To‘g‘ri gap'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Yulduzlar soni'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='words',
            field=models.JSONField(verbose_name='Aralashtirilgan so‘zlar'),
        ),
    ]
